# Generated by Django 3.0 on 2022-04-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0002_auto_20220424_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=32)),
                ('image', models.URLField()),
                ('early_decision', models.DateField()),
                ('early_action', models.DateField()),
                ('regular_decision', models.DateField()),
                ('app_home_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrackCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('T', 'Tracking'), ('I', 'Interested'), ('A', 'Applying'), ('D', 'Applied')], default='T', max_length=1)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.College')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
                ('in_progress', models.BooleanField()),
                ('hold', models.BooleanField()),
                ('early_decision', models.BooleanField()),
                ('early_action', models.BooleanField()),
                ('regular_decision', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Application')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.College')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='track_colleges',
            field=models.ManyToManyField(through='college_api.TrackCollege', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='college_applications',
            field=models.ManyToManyField(through='college_api.CollegeApplication', to='college_api.College'),
        ),
    ]
