# Generated by Django 3.0 on 2022-04-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0003_auto_20220424_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('Y', 'Normal'), ('P', 'Soothing'), ('O', 'NeedsAction'), ('G', 'WorkingOn'), ('B', 'LookAtMe'), ('R', 'AlertNOW')], default='Y', max_length=1)),
                ('due_date', models.DateField()),
                ('complete', models.BooleanField()),
                ('working_on', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Application')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Task')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='application_tasks',
            field=models.ManyToManyField(through='college_api.ApplicationTask', to='college_api.Task'),
        ),
    ]
