# Generated by Django 3.0 on 2022-04-24 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0004_auto_20220424_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_application_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tasks', to='college_api.Application'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='college_api.Task'),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_app', to='college_api.Application'),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_picked', to='college_api.College'),
        ),
        migrations.AlterField(
            model_name='trackcollege',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_monitored', to='college_api.College'),
        ),
    ]
