# Generated by Django 3.0 on 2022-04-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0005_auto_20220424_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='working_on',
            field=models.BooleanField(default=False),
        ),
    ]
