# Generated by Django 3.0 on 2022-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0006_auto_20220425_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='app_home_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='early_action',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='early_decision',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='regular_decision',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='date_submitted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='early_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='early_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='regular_decision',
            field=models.BooleanField(default=True),
        ),
    ]
