# Generated by Django 3.0 on 2022-04-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0007_auto_20220425_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtask',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
