# Generated by Django 3.0 on 2022-04-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0008_auto_20220425_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='early_action',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='early_decision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='regular_decision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
