# Generated by Django 3.0 on 2022-04-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0010_auto_20220426_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtask',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_tasks', to='college_api.Application'),
        ),
        migrations.AlterField(
            model_name='applicationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='todo', to='college_api.Task'),
        ),
    ]
